
# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch:

name: Create Image Pull Secret

jobs:
  build:
    
    name: 'Create Image Pull Secret'
    runs-on: ubuntu-latest
    steps:
    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: 'Create Secret'
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_URL: ec2-3-120-174-108.eu-central-1.compute.amazonaws.com
      run: |
        echo "$SSH_KEY" > private_key && chmod 400 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ec2-user@$EC2_URL
        kubectl create secret docker-registry image-pull-secret --docker-server=275852535211.dkr.ecr.eu-central-1.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password) --namespace=default
