
# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch:

name: Create Image Pull Secret

jobs:
  build:
    name: 'Create Image Pull Secret'
    runs-on: ubuntu-latest
    steps:
    - name: 'Create Secret'
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$SSH_KEY" | tr -d '\r' > ec2.pem
        chmod 400 ec2.pem
        ssh -i ec2.pem root@ec2-3-120-174-108.eu-central-1.compute.amazonaws.com
        kubectl create secret docker-registry image-pull-secret \
          --docker-server=275852535211.dkr.ecr.eu-central-1.amazonaws.com \
          --docker-username=AWS \
          --docker-password=$(aws ecr get-login-password) \
          --namespace=default
